version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configd

  cndstr-app-mongo:
    container_name: cndstr-app-mongo
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    networks:
      - default
